export type Product = { slug: string; name: string; category: string; price: number; summary: string; description: string; image: string; tag?: string; occasion: string; flowers: string; };
export const products: Product[] = [
  { slug: "maison-rose", name: "메종 로즈", category: "부케", price: 69000, summary: "클래식 로즈와 계절 소재", description: "한 송이씩 표정이 다른 가든 로즈와 크림 리시안셔스를 겹겹이 담았습니다. 축하와 고백, 오래 기억될 날에 가장 잘 어울리는 차화의 시그니처 부케입니다.", image: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?auto=format&fit=crop&w=1000&q=85", tag: "BEST", occasion: "축하", flowers: "가든 로즈, 리시안셔스, 스카비오사, 계절 그린" },
  { slug: "apricot-day", name: "애프리콧 데이", category: "부케", price: 58000, summary: "살구빛 카네이션과 프릴 튤립", description: "가벼운 설렘을 전하고 싶은 날을 위해 살구, 피치, 크림색 소재만 골라 구성했습니다. 편안한 온기가 오래 남는 부케입니다.", image: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=1000&q=85", occasion: "감사", flowers: "카네이션, 튤립, 라넌큘러스, 유칼립투스" },
  { slug: "verdant-vase", name: "버던트 베이스", category: "화병꽃", price: 82000, summary: "깊은 초록과 백합의 균형", description: "공간을 조용히 정돈하는 그린과 깨끗한 꽃을 화병에 바로 꽂아 전합니다. 개업과 이사, 사무실 선물로 추천합니다.", image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1000&q=85", tag: "NEW", occasion: "개업", flowers: "오리엔탈 백합, 아스틸베, 계절 그린" },
  { slug: "winter-letter", name: "윈터 레터", category: "플라워 박스", price: 75000, summary: "버건디와 크림의 다정한 대비", description: "열었을 때 가장 먼저 마음이 전달되도록, 낮고 풍성한 플라워 박스에 계절의 짙은 색을 담았습니다.", image: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=1000&q=85", occasion: "생일", flowers: "다알리아, 장미, 카네이션, 왁스플라워" },
  { slug: "softly-yours", name: "소프틀리 유어스", category: "부케", price: 64000, summary: "연한 핑크와 들꽃의 결", description: "짧은 안부에도 충분한 마음이 되도록, 여린 핑크 톤과 자연스러운 들꽃 소재를 부드럽게 묶었습니다.", image: "https://images.unsplash.com/photo-1494336934272-f0e7f74de7d3?auto=format&fit=crop&w=1000&q=85", occasion: "안부", flowers: "스프레이 로즈, 아스트란티아, 계절 초화" },
  { slug: "ceremony-green", name: "세레모니 그린", category: "기업/행사", price: 120000, summary: "행사를 위한 초록의 리듬", description: "브랜드 행사와 오픈을 위해 공간의 공기를 바꾸는 대형 어레인지먼트입니다. 현장 규모와 예산에 맞춘 상담 주문이 가능합니다.", image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1000&q=85", occasion: "기업", flowers: "계절 꽃, 수국, 수입 그린 소재" },
];
export const formatPrice = (price: number) => `${price.toLocaleString("ko-KR")}원`;
